// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/main.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MoveRequest struct {
	XInitPos             int32    `protobuf:"varint,1,opt,name=XInitPos,proto3" json:"XInitPos,omitempty"`
	YInitPos             int32    `protobuf:"varint,2,opt,name=YInitPos,proto3" json:"YInitPos,omitempty"`
	XFinalPos            int32    `protobuf:"varint,3,opt,name=XFinalPos,proto3" json:"XFinalPos,omitempty"`
	YFinalPos            int32    `protobuf:"varint,4,opt,name=YFinalPos,proto3" json:"YFinalPos,omitempty"`
	Id                   string   `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveRequest) Reset()         { *m = MoveRequest{} }
func (m *MoveRequest) String() string { return proto.CompactTextString(m) }
func (*MoveRequest) ProtoMessage()    {}
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4cf25e25a1b9d49, []int{0}
}

func (m *MoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveRequest.Unmarshal(m, b)
}
func (m *MoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveRequest.Marshal(b, m, deterministic)
}
func (m *MoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveRequest.Merge(m, src)
}
func (m *MoveRequest) XXX_Size() int {
	return xxx_messageInfo_MoveRequest.Size(m)
}
func (m *MoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MoveRequest proto.InternalMessageInfo

func (m *MoveRequest) GetXInitPos() int32 {
	if m != nil {
		return m.XInitPos
	}
	return 0
}

func (m *MoveRequest) GetYInitPos() int32 {
	if m != nil {
		return m.YInitPos
	}
	return 0
}

func (m *MoveRequest) GetXFinalPos() int32 {
	if m != nil {
		return m.XFinalPos
	}
	return 0
}

func (m *MoveRequest) GetYFinalPos() int32 {
	if m != nil {
		return m.YFinalPos
	}
	return 0
}

func (m *MoveRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type MoveAnswer struct {
	XInitPos             int32    `protobuf:"varint,1,opt,name=XInitPos,proto3" json:"XInitPos,omitempty"`
	YInitPos             int32    `protobuf:"varint,2,opt,name=YInitPos,proto3" json:"YInitPos,omitempty"`
	XFinalPos            int32    `protobuf:"varint,3,opt,name=XFinalPos,proto3" json:"XFinalPos,omitempty"`
	YFinalPos            int32    `protobuf:"varint,4,opt,name=YFinalPos,proto3" json:"YFinalPos,omitempty"`
	WhiteTurn            bool     `protobuf:"varint,5,opt,name=WhiteTurn,proto3" json:"WhiteTurn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveAnswer) Reset()         { *m = MoveAnswer{} }
func (m *MoveAnswer) String() string { return proto.CompactTextString(m) }
func (*MoveAnswer) ProtoMessage()    {}
func (*MoveAnswer) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4cf25e25a1b9d49, []int{1}
}

func (m *MoveAnswer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveAnswer.Unmarshal(m, b)
}
func (m *MoveAnswer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveAnswer.Marshal(b, m, deterministic)
}
func (m *MoveAnswer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveAnswer.Merge(m, src)
}
func (m *MoveAnswer) XXX_Size() int {
	return xxx_messageInfo_MoveAnswer.Size(m)
}
func (m *MoveAnswer) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveAnswer.DiscardUnknown(m)
}

var xxx_messageInfo_MoveAnswer proto.InternalMessageInfo

func (m *MoveAnswer) GetXInitPos() int32 {
	if m != nil {
		return m.XInitPos
	}
	return 0
}

func (m *MoveAnswer) GetYInitPos() int32 {
	if m != nil {
		return m.YInitPos
	}
	return 0
}

func (m *MoveAnswer) GetXFinalPos() int32 {
	if m != nil {
		return m.XFinalPos
	}
	return 0
}

func (m *MoveAnswer) GetYFinalPos() int32 {
	if m != nil {
		return m.YFinalPos
	}
	return 0
}

func (m *MoveAnswer) GetWhiteTurn() bool {
	if m != nil {
		return m.WhiteTurn
	}
	return false
}

type ConnectRequest struct {
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectRequest) Reset()         { *m = ConnectRequest{} }
func (m *ConnectRequest) String() string { return proto.CompactTextString(m) }
func (*ConnectRequest) ProtoMessage()    {}
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4cf25e25a1b9d49, []int{2}
}

func (m *ConnectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectRequest.Unmarshal(m, b)
}
func (m *ConnectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectRequest.Marshal(b, m, deterministic)
}
func (m *ConnectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectRequest.Merge(m, src)
}
func (m *ConnectRequest) XXX_Size() int {
	return xxx_messageInfo_ConnectRequest.Size(m)
}
func (m *ConnectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectRequest proto.InternalMessageInfo

func (m *ConnectRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ConnectRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ConnectResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Colour               string   `protobuf:"bytes,2,opt,name=colour,proto3" json:"colour,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectResponse) Reset()         { *m = ConnectResponse{} }
func (m *ConnectResponse) String() string { return proto.CompactTextString(m) }
func (*ConnectResponse) ProtoMessage()    {}
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4cf25e25a1b9d49, []int{3}
}

func (m *ConnectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectResponse.Unmarshal(m, b)
}
func (m *ConnectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectResponse.Marshal(b, m, deterministic)
}
func (m *ConnectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectResponse.Merge(m, src)
}
func (m *ConnectResponse) XXX_Size() int {
	return xxx_messageInfo_ConnectResponse.Size(m)
}
func (m *ConnectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectResponse proto.InternalMessageInfo

func (m *ConnectResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ConnectResponse) GetColour() string {
	if m != nil {
		return m.Colour
	}
	return ""
}

func init() {
	proto.RegisterType((*MoveRequest)(nil), "proto.MoveRequest")
	proto.RegisterType((*MoveAnswer)(nil), "proto.MoveAnswer")
	proto.RegisterType((*ConnectRequest)(nil), "proto.ConnectRequest")
	proto.RegisterType((*ConnectResponse)(nil), "proto.ConnectResponse")
}

func init() {
	proto.RegisterFile("api/main.proto", fileDescriptor_c4cf25e25a1b9d49)
}

var fileDescriptor_c4cf25e25a1b9d49 = []byte{
	// 312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x92, 0xcf, 0x4a, 0xf3, 0x40,
	0x14, 0xc5, 0x3b, 0xf9, 0x92, 0x7e, 0x9d, 0x5b, 0x48, 0x71, 0xd0, 0x52, 0x42, 0x17, 0x65, 0x56,
	0x59, 0x55, 0xb1, 0x3b, 0x37, 0xfe, 0x03, 0xc1, 0x85, 0x20, 0x83, 0x60, 0xeb, 0x2e, 0x36, 0x03,
	0x0e, 0xb6, 0x33, 0x31, 0x33, 0xb1, 0x7b, 0xdf, 0xc0, 0x17, 0xf0, 0x59, 0x65, 0x66, 0x92, 0x34,
	0xfa, 0x02, 0xae, 0x6e, 0xce, 0xf9, 0x85, 0x9b, 0x73, 0xef, 0x0d, 0xc4, 0x59, 0x21, 0x8e, 0xb7,
	0x99, 0x90, 0xf3, 0xa2, 0x54, 0x46, 0x91, 0xc8, 0x15, 0xfa, 0x89, 0x60, 0x78, 0xa7, 0xde, 0x39,
	0xe3, 0x6f, 0x15, 0xd7, 0x86, 0x24, 0x30, 0x58, 0xde, 0x4a, 0x61, 0xee, 0x95, 0x9e, 0xa0, 0x19,
	0x4a, 0x23, 0xd6, 0x6a, 0xcb, 0x56, 0x0d, 0x0b, 0x3c, 0x6b, 0x34, 0x99, 0x02, 0x5e, 0xde, 0x08,
	0x99, 0x6d, 0x2c, 0xfc, 0xe7, 0xe0, 0xde, 0xb0, 0x74, 0xd5, 0xd2, 0xd0, 0xd3, 0xd6, 0x20, 0x31,
	0x04, 0x22, 0x9f, 0x44, 0x33, 0x94, 0x62, 0x16, 0x88, 0x9c, 0x7e, 0x21, 0x00, 0x9b, 0xe9, 0x52,
	0xea, 0x1d, 0x2f, 0xff, 0x24, 0xd2, 0x14, 0xf0, 0xe3, 0x8b, 0x30, 0xfc, 0xa1, 0x2a, 0xa5, 0x4b,
	0x36, 0x60, 0x7b, 0x83, 0x5e, 0x40, 0x7c, 0xad, 0xa4, 0xe4, 0x6b, 0xd3, 0xac, 0x8d, 0x40, 0x28,
	0xb3, 0x2d, 0x77, 0x19, 0x30, 0x73, 0xcf, 0x36, 0x5b, 0x91, 0x69, 0xbd, 0x53, 0x65, 0xee, 0x3e,
	0x8f, 0x59, 0xab, 0xe9, 0x39, 0x8c, 0xda, 0x0e, 0xba, 0x50, 0x52, 0x73, 0x72, 0x08, 0x91, 0x51,
	0xaf, 0x5c, 0xba, 0x19, 0x31, 0xf3, 0x82, 0x8c, 0xa1, 0xbf, 0x56, 0x1b, 0x55, 0x95, 0x75, 0xeb,
	0x5a, 0x9d, 0x7e, 0x20, 0x18, 0x69, 0x2e, 0xf3, 0xee, 0xed, 0x16, 0x10, 0x5a, 0x49, 0x88, 0x3f,
	0xf1, 0xbc, 0xc3, 0x92, 0x83, 0x8e, 0xe7, 0xf7, 0x4a, 0x7b, 0x29, 0x3a, 0x41, 0xe4, 0x0c, 0xfe,
	0xd7, 0x49, 0xc8, 0x51, 0xfd, 0xce, 0xcf, 0xd9, 0x92, 0xf1, 0x6f, 0xdb, 0x07, 0xa6, 0xbd, 0xab,
	0xe1, 0x13, 0xb6, 0x7f, 0x95, 0xc3, 0xcf, 0x7d, 0x57, 0x16, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x01, 0x3c, 0x09, 0xa9, 0x69, 0x02, 0x00, 0x00,
}
