// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: api/main.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MoveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	XInitPos  int32  `protobuf:"varint,1,opt,name=XInitPos,proto3" json:"XInitPos,omitempty"`
	YInitPos  int32  `protobuf:"varint,2,opt,name=YInitPos,proto3" json:"YInitPos,omitempty"`
	XFinalPos int32  `protobuf:"varint,3,opt,name=XFinalPos,proto3" json:"XFinalPos,omitempty"`
	YFinalPos int32  `protobuf:"varint,4,opt,name=YFinalPos,proto3" json:"YFinalPos,omitempty"`
	Id        string `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *MoveRequest) Reset() {
	*x = MoveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_main_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveRequest) ProtoMessage() {}

func (x *MoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_main_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveRequest.ProtoReflect.Descriptor instead.
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return file_api_main_proto_rawDescGZIP(), []int{0}
}

func (x *MoveRequest) GetXInitPos() int32 {
	if x != nil {
		return x.XInitPos
	}
	return 0
}

func (x *MoveRequest) GetYInitPos() int32 {
	if x != nil {
		return x.YInitPos
	}
	return 0
}

func (x *MoveRequest) GetXFinalPos() int32 {
	if x != nil {
		return x.XFinalPos
	}
	return 0
}

func (x *MoveRequest) GetYFinalPos() int32 {
	if x != nil {
		return x.YFinalPos
	}
	return 0
}

func (x *MoveRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MoveAnswer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	XInitPos  int32 `protobuf:"varint,1,opt,name=XInitPos,proto3" json:"XInitPos,omitempty"`
	YInitPos  int32 `protobuf:"varint,2,opt,name=YInitPos,proto3" json:"YInitPos,omitempty"`
	XFinalPos int32 `protobuf:"varint,3,opt,name=XFinalPos,proto3" json:"XFinalPos,omitempty"`
	YFinalPos int32 `protobuf:"varint,4,opt,name=YFinalPos,proto3" json:"YFinalPos,omitempty"`
	WhiteTurn bool  `protobuf:"varint,5,opt,name=WhiteTurn,proto3" json:"WhiteTurn,omitempty"`
}

func (x *MoveAnswer) Reset() {
	*x = MoveAnswer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_main_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveAnswer) ProtoMessage() {}

func (x *MoveAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_api_main_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveAnswer.ProtoReflect.Descriptor instead.
func (*MoveAnswer) Descriptor() ([]byte, []int) {
	return file_api_main_proto_rawDescGZIP(), []int{1}
}

func (x *MoveAnswer) GetXInitPos() int32 {
	if x != nil {
		return x.XInitPos
	}
	return 0
}

func (x *MoveAnswer) GetYInitPos() int32 {
	if x != nil {
		return x.YInitPos
	}
	return 0
}

func (x *MoveAnswer) GetXFinalPos() int32 {
	if x != nil {
		return x.XFinalPos
	}
	return 0
}

func (x *MoveAnswer) GetYFinalPos() int32 {
	if x != nil {
		return x.YFinalPos
	}
	return 0
}

func (x *MoveAnswer) GetWhiteTurn() bool {
	if x != nil {
		return x.WhiteTurn
	}
	return false
}

type ConnectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_main_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_main_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_api_main_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConnectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConnectRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ConnectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token  string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Colour string `protobuf:"bytes,2,opt,name=colour,proto3" json:"colour,omitempty"`
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_main_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_main_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_api_main_proto_rawDescGZIP(), []int{3}
}

func (x *ConnectResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ConnectResponse) GetColour() string {
	if x != nil {
		return x.Colour
	}
	return ""
}

var File_api_main_proto protoreflect.FileDescriptor

var file_api_main_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x91, 0x01, 0x0a, 0x0b, 0x4d, 0x6f, 0x76, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x58, 0x49, 0x6e, 0x69, 0x74,
	0x50, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x58, 0x49, 0x6e, 0x69, 0x74,
	0x50, 0x6f, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x59, 0x49, 0x6e, 0x69, 0x74, 0x50, 0x6f, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x59, 0x49, 0x6e, 0x69, 0x74, 0x50, 0x6f, 0x73, 0x12,
	0x1c, 0x0a, 0x09, 0x58, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x50, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x58, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x50, 0x6f, 0x73, 0x12, 0x1c, 0x0a,
	0x09, 0x59, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x50, 0x6f, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x09, 0x59, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x50, 0x6f, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x9e, 0x01, 0x0a, 0x0a,
	0x4d, 0x6f, 0x76, 0x65, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x58, 0x49,
	0x6e, 0x69, 0x74, 0x50, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x58, 0x49,
	0x6e, 0x69, 0x74, 0x50, 0x6f, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x59, 0x49, 0x6e, 0x69, 0x74, 0x50,
	0x6f, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x59, 0x49, 0x6e, 0x69, 0x74, 0x50,
	0x6f, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x58, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x50, 0x6f, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x58, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x50, 0x6f, 0x73,
	0x12, 0x1c, 0x0a, 0x09, 0x59, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x50, 0x6f, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x59, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x50, 0x6f, 0x73, 0x12, 0x1c,
	0x0a, 0x09, 0x57, 0x68, 0x69, 0x74, 0x65, 0x54, 0x75, 0x72, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x09, 0x57, 0x68, 0x69, 0x74, 0x65, 0x54, 0x75, 0x72, 0x6e, 0x22, 0x50, 0x0a, 0x0e,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x3f,
	0x0a, 0x0f, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6c, 0x6f, 0x75,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6c, 0x6f, 0x75, 0x72, 0x32,
	0x82, 0x01, 0x0a, 0x0f, 0x73, 0x65, 0x6e, 0x64, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x04, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x12, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x41, 0x6e, 0x73, 0x77,
	0x65, 0x72, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x3a, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x0b, 0x5a, 0x09, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_main_proto_rawDescOnce sync.Once
	file_api_main_proto_rawDescData = file_api_main_proto_rawDesc
)

func file_api_main_proto_rawDescGZIP() []byte {
	file_api_main_proto_rawDescOnce.Do(func() {
		file_api_main_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_main_proto_rawDescData)
	})
	return file_api_main_proto_rawDescData
}

var file_api_main_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_main_proto_goTypes = []interface{}{
	(*MoveRequest)(nil),     // 0: proto.MoveRequest
	(*MoveAnswer)(nil),      // 1: proto.MoveAnswer
	(*ConnectRequest)(nil),  // 2: proto.ConnectRequest
	(*ConnectResponse)(nil), // 3: proto.ConnectResponse
}
var file_api_main_proto_depIdxs = []int32{
	0, // 0: proto.sendMoveRequest.Move:input_type -> proto.MoveRequest
	2, // 1: proto.sendMoveRequest.Connect:input_type -> proto.ConnectRequest
	1, // 2: proto.sendMoveRequest.Move:output_type -> proto.MoveAnswer
	3, // 3: proto.sendMoveRequest.Connect:output_type -> proto.ConnectResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_main_proto_init() }
func file_api_main_proto_init() {
	if File_api_main_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_main_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_main_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveAnswer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_main_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_main_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_main_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_main_proto_goTypes,
		DependencyIndexes: file_api_main_proto_depIdxs,
		MessageInfos:      file_api_main_proto_msgTypes,
	}.Build()
	File_api_main_proto = out.File
	file_api_main_proto_rawDesc = nil
	file_api_main_proto_goTypes = nil
	file_api_main_proto_depIdxs = nil
}
